alias c="clear"
alias ls="ls -G"
alias ll="ls -alG"
alias gitstatus="git status"
alias gitresetfile="git checkout --"
alias githardreset="git reset --hard HEAD"
alias gitclean="git clean"
alias gitpush="git push origin HEAD"
alias gitfetch="git fetch"
alias gitpull="git pull"
alias gitadd="git add"
alias gitaddall="git add -A"
alias gitcommit="git commit -m"
alias gitlog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias adbdevices="adb devices"
alias adbkill="adb kill-server"
alias adbstart="adb start-server"
alias reloadzshrc="source ~/.zshrc"

alias cddev="cd $DEV_PATH"
alias cdrepos="cd $REPOS_PATH"
