alias ll="ls -al"
alias gitresetfile="git checkout --"
alias githardreset="git reset --hard HEAD"
alias gitclean="git clean"
alias gitpush="git push"
alias gitfetch="git fetch"
alias gitgrab="git pull"
alias gitlog="git log"
alias gitbeautylog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias adbdevices="adb devices"
alias adbkill="adb kill-server"
alias adbstart="adb start-server"