export DEV_PATH=$HOME/dev
export REPOS_PATH=$DEV_PATH/repos
export BUILDS_PATH=$DEV_PATH/builds
export ZSHEBANG="#!/usr/bin/env zsh"
export SHEBANG="#!/usr/bin/env bash"
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export PATH="$HOME/.rd/bin:$PATH"
export PATH="$HOME/.pyenv/shims:$PATH"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$HOME/.codeium/windsurf/bin:$PATH"
