alias screendocker="screen $DOCKER_VM"
alias setjava12="export JAVA_HOME=`/usr/libexec/java_home -v 12`; java -version"
alias setjava11="export JAVA_HOME=`/usr/libexec/java_home -v 11`; java -version"
alias setjava10="export JAVA_HOME=`/usr/libexec/java_home -v 10`; java -version"
alias setjava9="export JAVA_HOME=`/usr/libexec/java_home -v 9`; java -version"
alias setjava8="export JAVA_HOME=`/usr/libexec/java_home -v 1.8`; java -version"
