ANDROID_PATH=~/Library/Android
ANDROID_SDK=$ANDROID_PATH/sdk
ANDROID_NDK=$ANDROID_PATH/ndk
ANDROID_HOME=$ANDROID_SDK
UNITY_PATH=/Applications/Unity
PATH=$PATH:$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools:$ANDROID_NDK:$UNITY_PATH/Unity.app/Contents/MacOS